spring:
  application:
    name: eureka-server

---
spring:
  #指定profile = peer1
  profiles: server1
server:
  port: 8761
eureka:
  instance:
    #指定当profile=peer1时,主机名是peer1
    hostname: eureka1
  client:
    serviceUrl:
      #将自己注册到peer2这个Eureka上去
      defaultZone: http://eureka2:8762/eureka/
---
spring:
  profiles: server2
server:
  port: 8762
eureka:
  instance:
    hostname: eureka2
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/